### ISSUE TITLE
If press enter on retry and then press escape a crash will happen and erase the whole data

### ISSUE THREAD

**Issue by AndZRi** [FunkinCrew/Funkin#2399]
### If you are playing the game in a browser, what site are you playing it from?

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
1. press enter to retry
2. wait until it's a bit dark
3. press escape
4. and there is your erased data including settings and scores

## Please describe your issue. Provide extensive detail and images if possible.
![image](https://github.com/FunkinCrew/Funkin/assets/68921308/e76192b2-4d96-4fc2-8ddf-a551d992d201)
![image](https://github.com/FunkinCrew/Funkin/assets/68921308/1acd8262-6607-432c-851c-6b4e1be05c49)

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting
Funkin.js:308917 Uncaught TypeError: Cannot read properties of null (reading 'set_x')
    at flixel_util_FlxTimer.onComplete (Funkin.js:148653:25)
    at flixel_util_FlxTimer.onLoopFinished (Funkin.js:114577:9)
    at flixel_util_FlxTimerManager.update (Funkin.js:114638:56)
    at flixel_FlxGame.update (Funkin.js:20939:12)
    at flixel_FlxGame.step (Funkin.js:20917:8)
    at flixel_FlxGame.onEnterFrame (Funkin.js:20853:10)
    at openfl_display_Stage.__dispatchEvent (Funkin.js:1194:15)
    at openfl_display_Stage.__dispatch (Funkin.js:2203:73)
    at openfl_display_Stage.__broadcastEvent (Funkin.js:308689:19)
    at openfl_display_Stage.__onLimeRender (Funkin.js:309783:8)

**Comment by Pyro0TV** [comment]
I found another bug _exactly_ like this, but rather than Escape, it's Backspace.
_**Windows/Firefox/Itch.io/0.3.2**_

I've also re-tried it on Windows/Chrome/Itch.io/0.3.2, and it gives the same error message. I have a small clip (I'm dogshit) of the Firefox/Itch version crashing.


https://github.com/FunkinCrew/Funkin/assets/141536178/ae813aaf-490d-4488-9763-abde25fd657f

Couldn't get the red-error message in console since then my screen froze and I had to brute-close. (not really sure, F12 didn't respond)

**Comment by Hundrec** [comment]
Sorry you lost your save data!
Are you able to reproduce this on the newest version: 0.5.2? 
If not, then we can close this issue.
