### ISSUE TITLE
[BUG] Pressing Enter and Backspace together on Freeplay freezes the game

### ISSUE THREAD

**Issue by jejeneurology** [FunkinCrew/Funkin#2944]
## Describe the bug
When I was in the menu of freeplay, I press Enter to choose a song and I press Backward at the same time as Enter by mistake,
it freezes the game in the main menu and I can't do something. For details : I played on the web version on Newgrounds

## To Reproduce
Press the button "Enter" and "Backward" of the keyboard at the exact same time only in the "Freeplay" menu
## Expected behavior
I was expecting the song I choose to start

## Additional context
Here the code in red of the console :
TypeError: Cannot read properties of null (reading 'color')
    at flixel_text_FlxText.set_color (Funkin.js:40055:26)
    at funkin_ui_freeplay_CapsuleText.flickerProgress (Funkin.js:210227:21)
    at flixel_util_FlxTimer.onLoopFinished (Funkin.js:116230:9)
    at flixel_util_FlxTimerManager.update (Funkin.js:116291:56)
    at flixel_FlxGame.update (Funkin.js:22592:12)
    at flixel_FlxGame.step (Funkin.js:22570:8)
    at flixel_FlxGame.onEnterFrame (Funkin.js:22502:11)
    at openfl_display_Stage.__dispatchEvent (Funkin.js:1194:15)
    at openfl_display_Stage.__dispatch (Funkin.js:2203:73)
    at openfl_display_Stage.__broadcastEvent (Funkin.js:313630:19)

**Comment by EliteMasterEric** [comment]
Could not reproduce on web or desktop

**Comment by AbnormalPoof** [comment]
It is pretty precise. However, it is doable.

Web:

https://github.com/user-attachments/assets/0f98bf49-388f-45e1-96ee-73fdca3344a7

Desktop:

https://github.com/user-attachments/assets/dad46f08-96d9-42b9-933f-456ac0e6434e

**Comment by AbnormalPoof** [comment]
Still occurs
![screenshot-2024-10-17-22-55-14](https://github.com/user-attachments/assets/d47156c3-579e-4ba4-8c9c-6c4494f625c8)
 in v0.5.2.

**Comment by Hundrec** [comment]
Just reproduced this first try on 0.5.3
