### ISSUE TITLE
Bug Report: Chart editor closes when trying to open an extremely long song (4 h 18m 36.687s).

### ISSUE THREAD

**Issue by Shaunyman** [FunkinCrew/Funkin#3702]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

This is basically a continuation from my previous issue [#3070](https://github.com/FunkinCrew/Funkin/issues/3070). This time, however, the game simply closes when trying to open the song. No error messages, no crash log, nothing. I was able to work around this issue by reducing the sample rate of the audio file to 34,601Hz from the standard 44,100Hz. Anything above 34,601Hz makes the game close immediately upon selection. I feel like this is going to be a very similar issue to [#3070](https://github.com/FunkinCrew/Funkin/issues/3070) where the integer limit is exceeded, but I'm not sure. It just feels exactly the same as it did back in v0.4.1 when I made the original issue. This song/chart will only continue to get larger as the game continues to develop and release more songs/charts, so I may be submitting more of these types of issues as the game's development continues... Issue [#3070](https://github.com/FunkinCrew/Funkin/issues/3070) was fixed with the release of v0.5.0. I'm not sure exactly what went into solving the issue, but I hope it can be done again! If not, I'll just have to keep lowering the sample rate of the song as more official songs get released. Let me know if you need anything from me!

https://github.com/user-attachments/assets/330f4fd9-cdba-4c9f-82d7-ac34c736121b

### Steps to Reproduce

Try to open a song in the chart editor that is 4 hours 18 minutes and 36.687 seconds long that uses a sample rate of 34,602Hz or more. The game should instantly close after selecting the song.

**Comment by Hundrec** [comment]
Respect for stress testing the engine to its max

**Comment by lemz1** [comment]
couldn't you make a script that just loads a song, and then everytime the song finishes the next difficulty is loaded and played. And when all variations and difficulties are finished, the next song is loaded. By doing that you dont need to create a large chart containing all songs, which is also better for memory usage

**Comment by Shaunyman** [comment]
> Respect for stress testing the engine to its max

Thank you XD

**Comment by lemz1** [comment]
> If I understood a word of what you just said, then maybe. But since I didn't, no. Maybe that's something _you_ could do, but me personally, no way lol.

being honest, i might actually make this script, since it seems like a fun little project. If i finish it, i'd just send it in here i guess.

**Comment by Shaunyman** [comment]
> > If I understood a word of what you just said, then maybe. But since I didn't, no. Maybe that's something _you_ could do, but me personally, no way lol.
> 
> being honest, i might actually make this script, since it seems like a fun little project. If i finish it, i'd just send it in here i guess.

Sounds cool to me! You'll have to teach me how to use it though since I don't know how. That's more advanced than anything I've ever done.

**Comment by AbnormalPoof** [comment]
> couldn't you make a script that just loads a song, and then everytime the song finishes the next difficulty is loaded and played. And when all variations and difficulties are finished, the next song is loaded. By doing that you dont need to create a large chart containing all songs, which is also better for memory usage

What about making a scripted custom week that is automatically populated with every song on every difficulty/variation? Though that’s basically the same thing now that I think about it.

**Comment by lemz1** [comment]
[marathonLOL.zip](https://github.com/user-attachments/files/17382806/marathonLOL.zip)

this is the marathon mod

it adds a song to freeplay called 'Marathon' (only available on hard)

everything should be working, hopefully. (i did a bit of testing, but not thoroughly)

**Comment by Shaunyman** [comment]
> from what i understood, the maraton is supposed to consist of all difficulties and variations. this means we cant use storymode, since it is tied to a specific difficulty and variation.

"the marathon is supposed to consist of all difficulties and variations." This is correct. In fact, there is also a specific order to the songs that I have written down in a separate text file. It's possible to do story mode if one gigantic chart is made (which is what I'm going to try to do to avoid a separate issue that arrived from this project [#3631](https://github.com/FunkinCrew/Funkin/issues/3631)). I'll have to check out your mod! If I can learn how to add songs to the freeplay menu from it, that would be awesome!

**Comment by NotHyper-474** [comment]
> I'm not sure exactly what went into solving the issue, but I hope it can be done again!

It was originally a bug in OpenFL, one of Funkin's backends, which was solved by simply upgrading it. 

Looking at the backtrace of this crash shows its rooted in Lime (another backend)'s external libraries, so I'm not sure if it's worth the trouble of solving it.
<details><summary>Backtrace</summary>
<pre>
#0  0x00007ffff6b39524 in ov_read_filter (vf=0x55555c3220f0, buffer=0x0, length=4096, bigendianp=0, word=2, sgned=1, bitstream=0x7fffffffaaa8, 
    filter=0x0, filter_param=0x0) at ./lib/vorbis/lib/vorbisfile.c:2032
#1  0x00007ffff6b39941 in ov_read (vf=0x55555c3220f0, buffer=0x0, length=4096, bigendianp=0, word=2, sgned=1, bitstream=0x7fffffffaaa8)
    at ./lib/vorbis/lib/vorbisfile.c:2099
#2  0x00007ffff5f37b57 in lime::OGG::Decode (resource=0x7fffffffab00, audioBuffer=0x7fffffffab40) at ./src/media/containers/OGG.cpp:64
#3  0x00007ffff5f488ff in lime::lime_audio_load_bytes (data=0x555563d82adc, buffer=0x555563d82b58) at ./src/ExternalInterface.cpp:396
#4  0x000055555677af08 in lime::media::AudioBuffer_obj::fromBytes (bytes=...) at ./src/lime/media/AudioBuffer.cpp:343
#5  0x0000555557934ddf in openfl::media::Sound_obj::loadCompressedDataFromByteArray (this=0x555563d82a70, bytes=..., bytesLength=125581428)
    at ./src/openfl/media/Sound.cpp:274
#6  0x00005555569f335b in funkin::util::assets::SoundUtil_obj::buildSoundFromBytes (input=...) at ./src/funkin/util/assets/SoundUtil.cpp:84
</pre>
</details>
